apiVersion: v1
kind: Pod
metadata:
  name: memoryhog-high
spec:
  containers:
  - name: memoryhog
    image: adamsandor83/memoryhog
    env:
      - name: PINKY_CONSUME_MB
        value: "700"
      - name: PINKY_RELEASE_AFTER_SEC
        value: "20"
      - name: PINKY_CONSUME_RATE
        value: "5"
      - name: JMX_HOSTNAME
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    resources:
        limits:
            memory: 1000Mi
        requests:
            memory: 1000Mi
    ports:
      - containerPort: 9999
        name: jmx

